sync update-resolv-conf script with Debian
The script apparently comes from Debian, but it looks really, really
old. There were changes done to the script since then including
improvements on error handling and refactoring that make the script
easier to read and audit.

The script content was synchronized with the OpenVPN 2.4.6-1 Debian
package, as available here:

https://sources.debian.org/data/main/o/openvpn/2.4.6-1/debian/update-resolv-conf

diff --git a/pages/vpn/vpn-red/update-resolv-conf b/pages/vpn/vpn-red/update-resolv-conf
--- a/pages/vpn/vpn-red/update-resolv-conf
+++ b/pages/vpn/vpn-red/update-resolv-conf
@@ -1,47 +1,63 @@
 #!/bin/bash
-#
-# Parses DHCP options from OpenVPN to update resolv.conf.
-# To use set as 'up' and 'down' script in your openvpn config:
+# 
+# Parses DHCP options from openvpn to update resolv.conf
+# To use set as 'up' and 'down' script in your openvpn *.conf:
 # up /etc/openvpn/update-resolv-conf
 # down /etc/openvpn/update-resolv-conf
 #
-# credit:
-# * Thomas Hood <jdthood@yahoo.co.uk>
-# * Chris Hanson
-# * chlauber@bnc.ch
-#
-# Licensed under the GNU GPL
+# Used snippets of resolvconf script by Thomas Hood and Chris Hanson.
+# Licensed under the GNU GPL.  See /usr/share/common-licenses/GPL. 
 # 
+# Example envs set from openvpn:
+#
+#     foreign_option_1='dhcp-option DNS 193.43.27.132'
+#     foreign_option_2='dhcp-option DNS 193.43.27.133'
+#     foreign_option_3='dhcp-option DOMAIN be.bnc.ch'
+#
 
-[ -x /sbin/resolvconf ] || exit 0 
+if [ ! -x /sbin/resolvconf ] ; then
+    logger "[OpenVPN:update-resolve-conf] missing binary /sbin/resolvconf";
+    exit 0;
+fi
 
-case $script_type in 
+[ "$script_type" ] || exit 0
+[ "$dev" ] || exit 0
+
+split_into_parts()
+{
+	part1="$1"
+	part2="$2"
+	part3="$3"
+}
+
+case "$script_type" in
   up)
-    for optionname in ${!foreign_option_*} ; do
-      option="${!optionname}"
-      echo $option
-      part1=$(echo "$option" | cut -d " " -f 1)
-      if [ "$part1" == "dhcp-option" ] ; then
-        part2=$(echo "$option" | cut -d " " -f 2)
-        part3=$(echo "$option" | cut -d " " -f 3)
-        if [ "$part2" == "DNS" ] ; then
-          IF_DNS_NAMESERVERS="$IF_DNS_NAMESERVERS $part3"
-        fi
-        if [ "$part2" == "DOMAIN" ] ; then
-          IF_DNS_SEARCH="$part3"
-        fi
-      fi
-    done
-    R=""
-    if [ "$IF_DNS_SEARCH" ] ; then
-      R="${R}search $IF_DNS_SEARCH"
-    fi
-    for NS in $IF_DNS_NAMESERVERS ; do
-      R="${R}nameserver $NS"
-    done
-    echo -n "$R" | /sbin/resolvconf -a "${dev}.inet"
-    ;;
+	NMSRVRS=""
+	SRCHS=""
+	foreign_options=$(printf '%s\n' ${!foreign_option_*} | sort -t _ -k 3 -g)
+	for optionvarname in ${foreign_options} ; do
+		option="${!optionvarname}"
+		echo "$option"
+		split_into_parts $option
+		if [ "$part1" = "dhcp-option" ] ; then
+			if [ "$part2" = "DNS" ] ; then
+				NMSRVRS="${NMSRVRS:+$NMSRVRS }$part3"
+			elif [ "$part2" = "DOMAIN" ] ; then
+				SRCHS="${SRCHS:+$SRCHS }$part3"
+			fi
+		fi
+	done
+	R=""
+	[ "$SRCHS" ] && R="search $SRCHS
+"
+	for NS in $NMSRVRS ; do
+        	R="${R}nameserver $NS
+"
+	done
+	echo -n "$R" | /sbin/resolvconf -a "${dev}.openvpn"
+	;;
   down)
-    /sbin/resolvconf -d "${dev}.inet"
-    ;;
-esac 
+	/sbin/resolvconf -d "${dev}.openvpn"
+	;;
+esac
+
